services:
  web:
    build:
      context: ./jenkins-front/gpds
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./jenkins-front/gpds/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
  app:
    build:
      context: ./jenkins-back/gpds-autos
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/autos-10a
      SPRING_DATASOURCE_USERNAME: autos
      SPRING_DATASOURCE_PASSWORD: passwordautos
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8080"
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: autos-10a
      MYSQL_USER: autos
      MYSQL_PASSWORD: passwordautos
    volumes:
      - ./jenkins-back/mysql-data:/var/lib/mysql
networks:
  app-network:
    driver: bridge